## Numpy

Numpy ist ein sehr mächtiges Modul für viele mathematische Berechnungen

In [37]:
import numpy as np

### Matrizen

Eine Matrix ist eine 2-dimensional Liste. Ohne numpy können wir eine Matrix als Liste von Listen implementieren.

In [38]:
a = [[0,1,2],[3,4,5],[6,7,8]]
for zeile in a:
    print(zeile)

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


Der Zugriff auf die 1.Zeile und 3.Spalte erfolgt durch 2 Indizes, die nacheinander in eckigen Klammern stehen.


In [39]:
x = a[0][2]
print(x)

2


Mit numpy können wir solche Matrizen einfacher erzeugen, einfacher auf die Elemente zugreifen und haben mehr Möglichkeiten mit den Matrizen zu arbeiten.

In [40]:

a = np.array(range(9)).reshape(3,3)    # reshape: zeilen, spalten
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
x = a[0,2]                  # wir benötigen nur eine eckige Klammer
print(x)

2


Eine mit festen Werten erzeugen:

In [42]:
a = np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [43]:
a = np.zeros((4,5),dtype = 'uint')
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [44]:
a = np.full((4, 5), 2)
print(a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


#### Slicing mit numpy

Wenn wir Teile einer Matrix bearbeiten, machen wir zunächst eine Kopie der Ausgangsmatrix, um Seiteneffekte zu vermeiden.

In [45]:
a = np.array(range(81)).reshape(9,9)
print(a)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [46]:
# die Zeile mit Index 4
b = a.copy()[4,:]
print(b)

[36 37 38 39 40 41 42 43 44]


In [47]:
# die Zeilen mit Index 4-6
b = a.copy()[4:7,:]
print(b)

[[36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]]


In [48]:
# alle Zeilen mit geradem Index
b = a.copy()[::2,:]
print(b)

[[ 0  1  2  3  4  5  6  7  8]
 [18 19 20 21 22 23 24 25 26]
 [36 37 38 39 40 41 42 43 44]
 [54 55 56 57 58 59 60 61 62]
 [72 73 74 75 76 77 78 79 80]]


In [49]:
# die Spalten mit Index 4
b = a.copy()[:,4]
print(b)

[ 4 13 22 31 40 49 58 67 76]


In [50]:
# die erste und letzte Spalte
b = a.copy()[:,[0,-1]]
print(b)

[[ 0  8]
 [ 9 17]
 [18 26]
 [27 35]
 [36 44]
 [45 53]
 [54 62]
 [63 71]
 [72 80]]


In [51]:
# die mittlere 3x3 Matrix
a1 = a.copy()
a1 = a1[3:6,3:6]
print(a1)

[[30 31 32]
 [39 40 41]
 [48 49 50]]


##### Zeilen vertauschen

In [52]:
# Vertauschen zweier Zeilen
a1 = a.copy()                
a1[[0,2],:] = a1[[2,0],:]
print(a1)

[[18 19 20 21 22 23 24 25 26]
 [ 9 10 11 12 13 14 15 16 17]
 [ 0  1  2  3  4  5  6  7  8]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [53]:
# Vertauschen des oberen und unteren 3er-Zeilenblocks
a1 = a.copy()                
a1[[0,1,2,6,7,8],:] = a1[[6,7,8,0,1,2],:]
print(a1)

[[54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


##### Spalten vertauschen

In [54]:
# Vertauschen zweier Spalten
a1 = a.copy()                
a1[:,[0,1]] = a1[:,[1,0]]
print(a1)

[[ 1  0  2  3  4  5  6  7  8]
 [10  9 11 12 13 14 15 16 17]
 [19 18 20 21 22 23 24 25 26]
 [28 27 29 30 31 32 33 34 35]
 [37 36 38 39 40 41 42 43 44]
 [46 45 47 48 49 50 51 52 53]
 [55 54 56 57 58 59 60 61 62]
 [64 63 65 66 67 68 69 70 71]
 [73 72 74 75 76 77 78 79 80]]


In [55]:
# Vertauschen des linken und rechten 3er-Spaltenblocks
a1 = a.copy()                
a1[:,[0,1,2,6,7,8]] = a1[:,[6,7,8,0,1,2]]
print(a1)

[[ 6  7  8  3  4  5  0  1  2]
 [15 16 17 12 13 14  9 10 11]
 [24 25 26 21 22 23 18 19 20]
 [33 34 35 30 31 32 27 28 29]
 [42 43 44 39 40 41 36 37 38]
 [51 52 53 48 49 50 45 46 47]
 [60 61 62 57 58 59 54 55 56]
 [69 70 71 66 67 68 63 64 65]
 [78 79 80 75 76 77 72 73 74]]


##### Reihenfolge der Zeilen/Spalten umkehren


In [56]:
# Reihenfolge der Zeilen umkehren
a1 = a.copy()                
a1  = a1[::-1,:]
print(a1)

[[72 73 74 75 76 77 78 79 80]
 [63 64 65 66 67 68 69 70 71]
 [54 55 56 57 58 59 60 61 62]
 [45 46 47 48 49 50 51 52 53]
 [36 37 38 39 40 41 42 43 44]
 [27 28 29 30 31 32 33 34 35]
 [18 19 20 21 22 23 24 25 26]
 [ 9 10 11 12 13 14 15 16 17]
 [ 0  1  2  3  4  5  6  7  8]]


In [57]:
# Reihenfolge der Spalten umkehren
a1 = a.copy()                
a1  = a1[:,::-1]
print(a1)

[[ 8  7  6  5  4  3  2  1  0]
 [17 16 15 14 13 12 11 10  9]
 [26 25 24 23 22 21 20 19 18]
 [35 34 33 32 31 30 29 28 27]
 [44 43 42 41 40 39 38 37 36]
 [53 52 51 50 49 48 47 46 45]
 [62 61 60 59 58 57 56 55 54]
 [71 70 69 68 67 66 65 64 63]
 [80 79 78 77 76 75 74 73 72]]


##### Transposition

Bei der Transposition wird die k-te Zeile zur k-ten Spalte.

In [58]:
a1 = a.copy()
a1 = a1.T
print(a1)

[[ 0  9 18 27 36 45 54 63 72]
 [ 1 10 19 28 37 46 55 64 73]
 [ 2 11 20 29 38 47 56 65 74]
 [ 3 12 21 30 39 48 57 66 75]
 [ 4 13 22 31 40 49 58 67 76]
 [ 5 14 23 32 41 50 59 68 77]
 [ 6 15 24 33 42 51 60 69 78]
 [ 7 16 25 34 43 52 61 70 79]
 [ 8 17 26 35 44 53 62 71 80]]


##### Drehen um 90 Grad im Uhrzeigersinn

In [59]:
a1 = a.copy()
a1 = a1[::-1,:].T
print(a)
print()
print(a1)
 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]

[[72 63 54 45 36 27 18  9  0]
 [73 64 55 46 37 28 19 10  1]
 [74 65 56 47 38 29 20 11  2]
 [75 66 57 48 39 30 21 12  3]
 [76 67 58 49 40 31 22 13  4]
 [77 68 59 50 41 32 23 14  5]
 [78 69 60 51 42 33 24 15  6]
 [79 70 61 52 43 34 25 16  7]
 [80 71 62 53 44 35 26 17  8]]


##### Zuweisungen

In [60]:
a1 = a.copy()
a1[0,:] = 1                    # der ersten Zeile 1en zuweisen        
print(a1)

[[ 1  1  1  1  1  1  1  1  1]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [61]:
a1 = a.copy()
a1[0,:] = [1,2,9,6,7,4,2,3,0]   # der ersten Zeile verschiedene Werte zuweisen
print(a1)

[[ 1  2  9  6  7  4  2  3  0]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [62]:
a1 = a.copy()
a1[ a1%2==0 ] = 0              # alle geraden Zahlen auf 0 setzen
print(a1)

[[ 0  1  0  3  0  5  0  7  0]
 [ 9  0 11  0 13  0 15  0 17]
 [ 0 19  0 21  0 23  0 25  0]
 [27  0 29  0 31  0 33  0 35]
 [ 0 37  0 39  0 41  0 43  0]
 [45  0 47  0 49  0 51  0 53]
 [ 0 55  0 57  0 59  0 61  0]
 [63  0 65  0 67  0 69  0 71]
 [ 0 73  0 75  0 77  0 79  0]]


In [63]:
a1 = a.copy()
c = ([1,1,1],[3,4,5])
a1[c] = [-1,-2,-3]                    # einige Stellen anders setzen
print(a1)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 -1 -2 -3 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [64]:
a1 = a.copy()
c = (range(9),range(9))
a1[c] = -1              # die Diagonale auf -1 setzen
print(a1)

[[-1  1  2  3  4  5  6  7  8]
 [ 9 -1 11 12 13 14 15 16 17]
 [18 19 -1 21 22 23 24 25 26]
 [27 28 29 -1 31 32 33 34 35]
 [36 37 38 39 -1 41 42 43 44]
 [45 46 47 48 49 -1 51 52 53]
 [54 55 56 57 58 59 -1 61 62]
 [63 64 65 66 67 68 69 -1 71]
 [72 73 74 75 76 77 78 79 -1]]


#### Worte in ein Buchstaben-Rechteck einfügen

In [65]:
rows = 5
cols = 5
a = np.array(list('.'*rows*cols))
a = a.reshape(rows,cols)
a

array([['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### waagrecht von links nach rechts (O)

In [66]:
# wort an position (i,j) waagrecht
i, j = 0, 0
wort = list('TAG')
a[i,range(j,j+len(wort))] = wort
a


array([['T', 'A', 'G', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### waagrecht von rechts nach links (W)

In [67]:
i, j = 3, 3
a[i,range(j,j-len(wort),-1)] = wort
a

array([['T', 'A', 'G', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', 'G', 'A', 'T', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### von oben nach unten (S)

In [68]:
i, j = 2, 4
a[range(i,i+len(wort)),j] = wort
a

array([['T', 'A', 'G', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', 'T'],
       ['.', 'G', 'A', 'T', 'A'],
       ['.', '.', '.', '.', 'G']], dtype='<U1')

##### von unten nach oben (N)

In [69]:
i, j = 4, 3
a[range(i,i-len(wort),-1),j] = wort
a

array([['T', 'A', 'G', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', 'G', 'T'],
       ['.', 'G', 'A', 'A', 'A'],
       ['.', '.', '.', 'T', 'G']], dtype='<U1')

##### diagonal nach rechts unten (SO)

In [70]:
a = np.array(list('.'*rows*cols))
a = a.reshape(rows,cols)

i, j = 1, 0
a[range(i,i+len(wort)),range(j,j+len(wort))] = wort
a

array([['.', '.', '.', '.', '.'],
       ['T', '.', '.', '.', '.'],
       ['.', 'A', '.', '.', '.'],
       ['.', '.', 'G', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### diagonal nach rechts oben (NO)

In [71]:
i, j = 3, 0
a[range(i,i-len(wort),-1),range(j,j+len(wort))] = wort
a

array([['.', '.', '.', '.', '.'],
       ['T', '.', 'G', '.', '.'],
       ['.', 'A', '.', '.', '.'],
       ['T', '.', 'G', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### diagonal nach links oben (NW)

In [72]:
i, j = 2, 4
a[range(i,i-len(wort),-1),range(j,j-len(wort),-1)] = wort
a

array([['.', '.', 'G', '.', '.'],
       ['T', '.', 'G', 'A', '.'],
       ['.', 'A', '.', '.', 'T'],
       ['T', '.', 'G', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

##### diagonal nach links unten (SW)

In [73]:
i, j = 2, 4
a[range(i,i+len(wort)),range(j,j-len(wort),-1)] = wort
a

array([['.', '.', 'G', '.', '.'],
       ['T', '.', 'G', 'A', '.'],
       ['.', 'A', '.', '.', 'T'],
       ['T', '.', 'G', 'A', '.'],
       ['.', '.', 'G', '.', '.']], dtype='<U1')