## Backtracking Beispiele

[Video](https://youtu.be/0uYfWCeGGI4)

#### Jugendherberge

In der Jugendherberge organisiert man jeden Abend ein Lagerfeuer. Am ersten Abend setzen
sich alle Jugendlichen rund ums Feuer. Am zweiten Abend nehmen sie so Platz, dass die, 
die am ersten Abend Nachbarn waren, diesmal nicht nebeneinander sitzen. 
Bestimme alle Möglichkeiten, wie sie sich am zweiten Abend setzen können. Wir nehmen an,
dass sie am ersten Abend mit 1,2,3,...,n nummeriert sind.

<img src='lagerfeuer.png' width='800'>

Ein Kandidat erweitert eine Teillösung sinnvoll, wenn der Abstand zum letzten Element der Teillösung weder 1 noch n-1 ist.

<img src='lagerfeuer1.png' width='300'>

In [ ]:
def back(a):
    if isSolution(a):
        solutions.append(a.copy())
        return                       
    for cand in candidates(a):
        if isGood(cand,a):
            a.append(cand)
            back(a)
            a.pop()
                
def isSolution(a):
    '''
    returns: True, wenn die Teillösung a eine Lösung darstellt
    '''
    return len(a) == n
 
def candidates(a):
    '''
    returns: Liste von Entscheidungen, die die Teillösung a um eine Stufe erweitern können
    '''
    return list(range(1,n+1))
 
def isGood(cand, a):
    '''
    returns: True, wenn die Entscheidung cand die Teillösung a sinnvoll erweitert.
    '''
    if cand in a: return False
    if len(a) > 0 and (abs(a[-1]-cand) == 1 or abs(a[-1]-cand) == n-1): return False
    return True

In [ ]:
n = 5
solutions = []
back([])
print(f'Es gibt {len(solutions)} Möglichkeiten:')
for x in solutions:
    print(*x)

#### Referate
Die Erdkunde-Lehrerin möchte, dass die Schülerinnen und Schüler Referate halten, und verteilt die Themen.
Sie hat für die n Schülerinnen und Schüler m Themen vorbereitet (m <= n), von denen jedes mindestens einmal bearbeitet werden soll.
Welche Möglichkeiten gibt es, die Themen zu verteilen?

<img src='referate.png'>
 

In [ ]:
def back(a):
    if isSolution(a):
        solutions.append(a.copy())
        return
    for cand in candidates(a):
        if isGood(cand,a):
            a.append(cand)
            back(a)
            a.pop()
                
def isSolution(a):
    '''
    returns: True, wenn die Teillösung a eine Lösung darstellt
    '''
    return len(a) == n  

def candidates(a):  
    '''
    returns: Liste von Entscheidungen, die die Teillösung a um eine Stufe erweitern können
    '''
    return list(range(1,m+1))

def isGood(cand, a):
    '''
    returns: True, wenn die Entscheidung cand die Teillösung a sinnvoll erweitert.
    '''
    k = len(set(a) | {cand} )             # Anzahl schon vergebener verschiedenen Themen inclusive des aktuellen Kandidaten
    if m-k > n-len(a)-1: return False     # Anzahl noch zu vergebender Themen ist größer als die Anzahl der noch nicht vergebenen Schüler
    return True

           
n = 3
m = 2
solutions = []
back([])
print(f'Es gibt {len(solutions)} Möglichkeiten:')
for x in solutions:
    print(*x)

#### Haus vom Nikolaus

Wieviele Möglichkeiten gibt es, das Haus vom Nikolaus beginnend von der linken unteren Ecke zu zeichnen?
Das Haus hat 5 Knoten und 8 Kanten. Wir beginnen immer mit Knoten 0. Dann treffen wir 8 Entscheidungen (welches ist unser nächster Knoten?) Wir können schrittweise verfolgen, ob eine Entscheidung eine Teillösung sinnvoll erweitert. Dazu merken wir uns, welche Kanten wir bisher schon verbraucht haben.

<img src='nikolaus.png' width='600'>

In [ ]:
def back(a):
    if isSolution(a):
        solutions.append(a.copy())
        return
    for cand in candidates(a):
        if isGood(cand,a):
            used[(a[-1], cand)] = True    # diese Kanten sind verbraucht
            used[(cand, a[-1])] = True
            a.append(cand)
            back(a)
            a.pop()
            used[(a[-1], cand)] = False   # diese Kanten sind wieder unbenutzt
            used[(cand, a[-1])] = False
                
def isSolution(a):
    '''
    returns: True, wenn die Teillösung a eine Lösung darstellt
    '''
    return len(a) == 9

def candidates(a):
    '''
    returns: Liste von Entscheidungen, die die Teillösung a um eine Stufe erweitern
    '''
    return list(range(5))

def isGood(cand, a):
    '''
    returns: True, wenn die Entscheidung cand die Teillösung a sinnvoll erweitert.
    '''
    if (a[-1], cand) not in edges: return False
    return not used[(a[-1], cand)]

In [ ]:
edges = [(0,1),(1,0),(1,2),(2,1),(2,3),(3,2),(3,4),(4,3),(4,0),(0,4),(1,3),(3,1),(0,3),(3,0),(1,4),(4,1)]
used = {e: False for e in edges}

solutions = []
back([0])
print(len(solutions))
for k, sol in enumerate(solutions):
    print(f'{k+1:2}:', *sol)

#### Sudoku

Das Vorgehen überlegen machen wir uns an einem 4 x 4 Sudoku klar. Ein ordentliches Sudoku hat nur eine Lösung. Für den Fall, dass es doch mehrere Lösungen gibt, soll unser Programm alle Lösungen finden. 

<img src='sudoku1.png' width='500'>

Bei diesem Sudoku haben wir 11 Entscheidungen zu treffen. Als Kandidaten stehen uns die Zahlen von 1 bis 4 zur Verfügung. Für jeden Kandidaten können wir entscheiden, ob er die Teillösung sinnvoll erweitert.

In [ ]:
def back(a):
    if isSolution(a):
        solutions.append(a.copy())
        return
    for cand in candidates(a):
        if isGood(cand,a):
            a.append(cand)
            grid[leer[len(a)-1]] = cand
            back(a)
            grid[leer[len(a)-1]] = 0
            a.pop()
            
                
def isSolution(a):
    '''
    returns: True, wenn die Teillösung a eine Lösung darstellt
    '''
    return len(a) == len(leer)

def candidates(a):
    '''
    returns: Liste von Entscheidungen, die die Teillösung a um eine Stufe erweitern
    '''
    return list(range(1,n+1))

def isGood(cand, a):
    '''
    returns: True, wenn die Entscheidung cand die Teillösung a sinnvoll erweitert.
    '''
    x, y = leer[len(a)]     # die nächste zu füllende Leerstelle
    x1 = x - x%sn           # die linke obere Ecke  
    y1 = y - y%sn           # des zugehörigen Quadrats
    quadrat = grid[x1:x1+sn,y1:y1+sn].flatten()    
    if cand not in grid[x,:] and cand not in grid[:,y] and cand not in quadrat:
        return True
    return False

In [ ]:
data = '''
.2..
1.4.
...3
3...
'''

In [ ]:
zeilen = data.strip().split()
zeilen

In [ ]:
import numpy as np
n = len(zeilen)
sn = int(np.sqrt(n))
n, sn

In [ ]:
grid = np.zeros((n,n),dtype='int')
grid

In [ ]:
for x in range(n):
    for y in range(n):
        grid[x,y] = int(zeilen[x][y]) if zeilen[x][y].isdigit() else 0
grid

In der Liste leer speichern wir die Koordinaten der Leerfelder

In [ ]:
leer = []
for x in range(n):
    for y in range(n):
        if grid[x][y] == 0:
            leer.append((x,y))
print(leer)

Eine mögliche Lösung ist eine Liste der gleichen Länge wie leer, die jeder Leerstelle einen der möglichen Kandidaten 1,2,3,4 zuweist.

Um zu prüfen, ob ein Kandidat für die Leerstelle (x,y) gut ist, müssen wir auch das Quadrat überprüfen, in dem die Leerstelle liegt.

<img src='sudoku2.png' width='800'>

In [55]:
solutions = []
back([])
print(f'Anzahl der Lösungen: {len(solutions)}')

for i, solution in enumerate(solutions):
    grid0 = grid.copy()
    print(f'Lösung {i+1}:')
    for k in range(len(leer)):
        x, y = leer[k]
        grid0[x, y] = solution[k]
    print(grid0)

Anzahl der Lösungen: 1
Lösung 1:
[[4 2 3 1]
 [1 3 4 2]
 [2 4 1 3]
 [3 1 2 4]]


Das gesamte Programm:

In [57]:
# data = '''
# .2..
# 1.4.
# ...3
# 3...
# '''

# data = '''
# .2..
# 1.4.
# ....
# 3...
# '''

data = '''
...5.8936
.....3.54
9354...78
679.8...5
.......8.
.1..74..2
7..25....
4.....72.
...1.....
'''


zeilen = data.strip().split()
n = len(zeilen)
sn = int(np.sqrt(n))
print(n,sn)
grid = np.zeros((n,n),dtype='int')
for x in range(n):
    for y in range(n):
        grid[x,y] = int(zeilen[x][y]) if zeilen[x][y].isdigit() else 0

print(grid)
leer = []
for x in range(n):
    for y in range(n):
        if grid[x][y] == 0:
            leer.append((x,y))

solutions = []
back([])
print(f'Anzahl der Lösungen: {len(solutions)}')

for i, solution in enumerate(solutions):
    grid0 = grid.copy()
    print(f'Lösung {i+1}:')
    for k in range(len(leer)):
        x, y = leer[k]
        grid0[x, y] = solution[k]
    print(grid0)

9 3
[[0 0 0 5 0 8 9 3 6]
 [0 0 0 0 0 3 0 5 4]
 [9 3 5 4 0 0 0 7 8]
 [6 7 9 0 8 0 0 0 5]
 [0 0 0 0 0 0 0 8 0]
 [0 1 0 0 7 4 0 0 2]
 [7 0 0 2 5 0 0 0 0]
 [4 0 0 0 0 0 7 2 0]
 [0 0 0 1 0 0 0 0 0]]
Anzahl der Lösungen: 2
Lösung 1:
[[1 4 7 5 2 8 9 3 6]
 [2 8 6 7 9 3 1 5 4]
 [9 3 5 4 6 1 2 7 8]
 [6 7 9 3 8 2 4 1 5]
 [3 2 4 9 1 5 6 8 7]
 [5 1 8 6 7 4 3 9 2]
 [7 6 3 2 5 9 8 4 1]
 [4 5 1 8 3 6 7 2 9]
 [8 9 2 1 4 7 5 6 3]]
Lösung 2:
[[1 4 7 5 2 8 9 3 6]
 [8 6 2 7 9 3 1 5 4]
 [9 3 5 4 6 1 2 7 8]
 [6 7 9 3 8 2 4 1 5]
 [3 2 4 9 1 5 6 8 7]
 [5 1 8 6 7 4 3 9 2]
 [7 9 1 2 5 6 8 4 3]
 [4 5 6 8 3 9 7 2 1]
 [2 8 3 1 4 7 5 6 9]]


#### Alle Pfade

In einem DAG (directed acyclic graph) wollen wir alle Pfade von einem Startknoten zu einem Zielknoten bestimmen.
Wir fassen den Code gleich zusammen. Ob die Nachbarn eines Knoten als Menge oder als Liste (ohne Wiederholung) gegeben ist, spielt keine Rolle.

<img src='graph2.png' width='301'>

In [19]:
def allPaths(G, start, end):
    '''
    returns: Liste aller Pfade von start nach end in einem DAG (directed acyclic graph) G als Listen.

    G = {0:[4,3,1], 1:[3,2,4], 2:[3], 3:[4], 4:[]}
    >>> allPaths(G, 0, 4)
    [[0, 4], [0, 3, 4], [0, 1, 3, 4], [0, 1, 2, 3, 4], [0, 1, 4]]
    '''
    def back(a):
        if a[-1] == end:
             solutions.append(a.copy())
        for cand in G[a[-1]]:
            a.append(cand)
            back(a)
            a.pop()
                    
    solutions = []
    back([start])
    return solutions

In [24]:
G = {0:[4,3,1], 1:[3,2,4], 2:[3], 3:[4], 4:[]}
allPaths(G, 0, 4)

[[0, 4], [0, 3, 4], [0, 1, 3, 4], [0, 1, 2, 3, 4], [0, 1, 4]]

<img src='graph1.png' width='400'>

In [23]:
G = {1:{2,4,7}, 2:{3}, 3:set(), 4:{5}, 5:{6}, 6:set(), 7:{4,8}, 8:{5,9}, 9:{5}}
allPaths(G, 1, 6)

[[1, 4, 5, 6], [1, 7, 8, 9, 5, 6], [1, 7, 8, 5, 6], [1, 7, 4, 5, 6]]

#### Codingame
-  [Sudoku-Solver](https://www.codingame.com/training/medium/sudoku-solver)
-  [Finish The Eight Queens](https://www.codingame.com/training/medium/finish-the-eight-queens)